version: "2"
services:
  php:
    build:
      context: ./php
    image: slime/php:fpm
    restart: always
    volumes:
      - ./wwwroot:/var/www/html
      - ./php/conf.d/custom.ini:/usr/local/etc/php/conf.d/custom.ini
    container_name: php_fpm_7
    
  db:
    image: mysql
    restart: always
    volumes:
      - ./mysql/conf.d:/etc/mysql/conf.d
      - ./mysql/data:/var/lib/mysql
      - ./mysql/log:/var/log/mysql
    ports:
      - "3306:3306"
    expose:
      - "3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_PASSWORD=root
    container_name: mysql

  mainweb:
    image: nginx
    restart: always
    depends_on:
      - db
      - php
    volumes:
      - ./wwwroot:/var/www/html
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "8080:8080"
    expose:
      - "8080"
    container_name: nginx_mainweb
    links:
      - db