services:
  php:
    build:
      context: ./php
    image: slime/php:fpm
    restart: always
    environment:
      - XDEBUG_CLIENT_HOST=host.docker.internal
      - XDEBUG_CLIENT_PORT=9003
      - XDEBUG_IDE_KEY=docker
      - PUID=0
      - PGID=0
      - UMASK=022
    volumes:
      - ./wwwroot:/var/www/html:cached
      - ./php/conf.d/custom.ini:/usr/local/etc/php/conf.d/custom.ini
      - ./php/xdebug:/tmp/xdebug
    container_name: php_fpm_7

  db:
    image: mysql
    restart: always
    volumes:
      - ./mysql/conf.d:/etc/mysql/conf.d
      - ./mysql/data:/var/lib/mysql
      - ./mysql/log:/var/log/mysql
    ports:
      - "3306:3306"
    expose:
      - "3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_PASSWORD=root
    container_name: mysql

  mainweb:
    image: nginx
    restart: always
    depends_on:
      - db
      - php
    volumes:
      - ./wwwroot:/var/www/html:cached
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "8080:8080"
    expose:
      - "8080"
    container_name: nginx_mainweb
